app_backend:
    resource: "@AppBackendBundle/Resources/config/routing.yml"
    prefix:   /

app_user:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"