# src/Acme/UserBundle/Resources/config/doctrine/User.orm.yml
App\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO