services:
    sonata.admin.post:
        class: App\BackendBundle\Admin\SexoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Sexo" }
        arguments:
            - ~
            - App\BackendBundle\Entity\Sexo
            - ~
        calls:
#            - [ setTranslationDomain, [AcmeDemoBundle]]
            - [ setTranslationDomain, [AppBackendBundle]]
